### PR TITLE
Remove references to morfologik.stemming.PolishStemmer.DICTIONARY

### PR DESCRIPTION
**Pull request by tad-lispy**
Now I'm able to compile it and use with ES 1.1. Solves #4 for me. Credits go to Krzysztof Sobolewski.

### CODE REVIEW

**Comment by tad-lispy** [comment]
Please take a look and merge if possible @chytreg

**Comment by dgertych-monterail** [comment]
Hi, thx for you work. It looks OK. I found this https://github.com/morfologik/morfologik-stemming/commits/master/morfologik-polish/src/main/java/morfologik/stemming/PolishStemmer.java

So I understood the PolishStemmer.Dictionary deprecation.

Will do the release shortly.

**Comment by tad-lispy** [comment]
Cool, thanks :)

**Comment by pySilver** [comment]
@chytreg please merge it!

**Comment by dgertych-monterail** [comment]
Hi, i make the build via `mvn clean install` and it's everything ok.
But when I install the plugin I get from ES `java.lang.NoClassDefFoundError: morfologik/stemming/PolishStemmer`

@pySilver @lzrski Anyone knows how to deal with that?

**Comment by dgertych-monterail** [comment]
I'm not the Java developer but this helps me to run the plugin properly (https://github.com/monterail/elasticsearch-analysis-morfologik/commit/e6694bb0f8433e24d3bed2c2a2c10e16b6b53eb4)

**Pull request merged**
